### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by nonoonoo** [aleximorin/TimeDeltaBayesianModel#1]
Hi, thanks for your work, but when I debug the code I found that the netcdf_to_glacier module is missing in the fifth line of synthetic_example.py, could you please solve this bug? Thanks!

**Comment by aleximorin** [comment]
That's my mistake! Luckily it was an easy fix. Thank you for noticing it! Let me know if it works for you.

**Comment by nonoonoo** [comment]
Thank you very much for your reply and help！I'm using the latest pymc version, while debugging the code I found that some pymc modules don't work properly in my environment due to version issues, if it's convenient can you provide the version of python package needed to run this project?

**Comment by aleximorin** [comment]
You are right! This work is using [pymc2](https://github.com/pymc-devs/pymc2), it probably is the reason it is not working. I'll get to create a proper virtual environment using only the necessary packages and provide a .yaml file ASAP. Thank you for your interest and sorry for the trouble!

**Comment by Silevoem** [comment]
> You are right! This work is using [pymc2](https://github.com/pymc-devs/pymc2), it probably is the reason it is not working. I'll get to create a proper virtual environment using only the necessary packages and provide a .yaml file ASAP. Thank you for your interest and sorry for the trouble!

oh! I also encountered a similar problem recently, looking forward to your update!

**Comment by aleximorin** [comment]
Hey guys, sorry about the delay in my response. You can look at my response on this issue here: https://github.com/aleximorin/TimeDeltaBayesianModel/issues/2
